org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.7
loader_version=0.16.14

# Fabric API
fabric_version=0.119.4+1.21.4

# Dependencies
geckolib_version=4.8.5

# Mod Properties
mod_version=1.0.2-1.21.4-byMr712
maven_group=mielon.thesift
archives_base_name=MielonsTheSift-1.21.4-byMr712
